name:                esedicol
version:             0.1.0.0
github:              "githubuser/esedicol"
license:             BSD3
author:              "Emmanuel Sedicol"
maintainer:          "example@example.com"
copyright:           "2020 Emmanuel Sedicol"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/esedicol#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
    - Lib
    - Clean.Clean
    - TupleFunctions.Tuple
    - Voting.STV
    - Voting.AlternativeVoting
  other-modules: []
  dependencies:
    - split

executables:
  esedicol-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - esedicol

tests:
  esedicol-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - esedicol
